knp_paginator:
    page_range: 5                       # Nombre de pages affichées (ex: 1 2 3 4 5)
    default_options:
        page_name: page                 # Nom du paramètre dans l'URL (ex: ?page=2)
        sort_field_name: sort           # Nom du paramètre de tri
        sort_direction_name: direction  # Nom du paramètre de direction
        distinct: true
        filter_field_name: filterField  # Nom du paramètre de filtre
        filter_value_name: filterValue  # Nom du paramètre de valeur de filtre
    template:
        pagination: '@KnpPaginator/Pagination/tailwindcss_pagination.html.twig' # Le style Tailwind
        sortable: '@KnpPaginator/Pagination/sortable_link.html.twig'